### ISSUE TITLE
Using a different browser?

### ISSUE THREAD

**Issue by tomekr** [testdouble/cypress-rails#54]
Hello, thanks for the library! I noticed the default browser is Electron, is there a way to configure chrome and/or firefox headless?

I'm currently using the [cypress-io/github-action](https://github.com/cypress-io/github-action) Github Action

```
      - name: End-to-End Cypress Tests
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RAILS_PORT: 5678
        with:
          command: bundle exec rake cypress:run
```

I tried using the `with: browswer` syntax (https://github.com/cypress-io/github-action#browser) and it looks like that wouldn't override any config since we're using the custom `bundle exec rake cypress:run` command.

Is it possible to use an alternative browswer?
